spring:  
  application:
    name: order-service

server:  
  port: ${PORT:8090}

 
---
spring:
  config:
    activate:
      on-profile: dev
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration
  data:
    mongodb:
      host: 192.168.99.100
      port: 27017
      database: order
      username: micro
      password: micro123

---
spring:
  config:
    activate:
      on-profile: test
  data:
    mongodb:
      host: localhost
      port: 27017      

---
spring:
  config:
    activate:
      on-profile: no-discovery
eureka:
  client:
    enabled: false
account-service:
  ribbon:
    eureka:
      enable: false
    listOfServers: account-service:8080
customer-service:
  ribbon:
    eureka:
      enable: false
    listOfServers: customer-service:8080
product-service:
  ribbon:
    eureka:
      enable: false
    listOfServers: product-service:8080