spring:  
  application:
    name: account-service

server:  
  port: ${PORT:8091}
        
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
        
---
spring:
  profiles: dev
  data:
    mongodb:
      host: localhost
      port: 27017
      database: account
      username: micro
      password: micro123

---
spring:
  profiles: test
  data:
    mongodb:
      host: localhost
      port: 27017 

---
spring:
  profiles: no-discovery     
eureka:
  client:
    enabled: false
